image:
  file: .gitpod.dockerfile

ports:
# Web UI (static resources)
- port: 3000
# Server (API)
- port: 8080
# PostgreSQL
- port: 5432
  onOpen: ignore
# Elasticsearch
- port: 9200
  onOpen: ignore
- port: 9300
  onOpen: ignore

tasks:
- init: |
    # Build all components
    yarn --cwd cli
    yarn --cwd webui
    yarn --cwd webui build:dev
    server/gradlew -p server build downloadTestExtensions
  name: Server
  command: |
    if [[ $NPM_TOKEN ]]; then echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc; fi
    export OVSX_APP_PROFILE=$PWD/server/src/dev/resources/application-ovsx.properties
    echo "ovsx.webui.url=`gp url 3000`" >> $OVSX_APP_PROFILE
    echo "ovsx.elasticsearch.host=localhost:9200" >> $OVSX_APP_PROFILE
    export GITHUB_CALLBACK_URL=`gp url 8080 | sed s/https:/http:/`/login/oauth2/code/github
    echo "GitHub callback URL: $GITHUB_CALLBACK_URL"
    # Start Elasticsearch as background process
    $ES_HOME/bin/elasticsearch -d -p $ES_HOME/pid -Ediscovery.type=single-node -Expack.ml.enabled=false
    gp await-port 9200
    # Start the server application
    cd server
    ./gradlew runServer
- name: WebUI
  command: |
    gp await-port 8080
    # Start Express for serving frontend resources
    cd webui
    yarn start:dev
- name: Publisher
  command: |
    gp await-port 8080
    # Use the CLI to publish some test extensions to the running server
    export OVSX_REGISTRY_URL=http://localhost:8080
    export OVSX_PAT=super_token
    export PUBLISHERS="DotJoshJohnson eamodio Equinusocio felixfbecker formulahendry HookyQR ms-azuretools ms-mssql ms-python ms-vscode octref redhat ritwickdey sburg vscode Wscats"
    for pub in $PUBLISHERS; do cli/lib/ovsx create-namespace $pub; done
    find server/build/test-extensions-builtin -name '*.vsix' -exec cli/lib/ovsx publish '{}' \;
    find server/build/test-extensions -name '*.vsix' -exec cli/lib/ovsx publish '{}' \;
