{
 "title": "Open VSX",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "uri_prefix",
    "query": "RegistryAPI : /api/.*, VSCodeAdapter : /vscode/.*, UserAPI : /login|/user/.*, AdminAPI : /admin/.*, SitemapController : /sitemap.xml, Other : (?!/(sitemap.xml|login|((api|vscode|user|admin)/.*))).*"
   }
  ]
 },
 "panels": [
  {
   "title": "${uri_prefix} Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(rate(http_server_requests_seconds_count{job=\"Open VSX Registry input\", uri=~\"${uri_prefix:value}\"}[$__rate_interval]), \"exception\", \"\", \"exception\", \"(.*)\"), \"outcome\", \"\", \"outcome\", \"(.*)\"), \"status\", \"\", \"status\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "${uri_prefix} Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(rate(http_server_requests_seconds_count{job=\"Open VSX Registry input\", uri=~\"${uri_prefix:value}\", status=~\"(4|5)..\"}[$__rate_interval]), \"exception\", \"\", \"exception\", \"(.*)\"), \"outcome\", \"\", \"outcome\", \"(.*)\"), \"status\", \"\", \"status\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "${uri_prefix} Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(rate(http_server_requests_seconds_sum{job=\"Open VSX Registry input\", uri=~\"${uri_prefix:value}\"}[$__rate_interval]), \"exception\", \"\", \"exception\", \"(.*)\"), \"outcome\", \"\", \"outcome\", \"(.*)\"), \"status\", \"\", \"status\", \"(.*)\") / label_replace(label_replace(label_replace(rate(http_server_requests_seconds_count{job=\"Open VSX Registry input\", uri=~\"${uri_prefix:value}\"}[$__rate_interval]), \"exception\", \"\", \"exception\", \"(.*)\"), \"outcome\", \"\", \"outcome\", \"(.*)\"), \"status\", \"\", \"status\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}