{
 "title": "Upstream",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "uri_prefix",
    "label": "API",
    "query": "Any : .*, RegistryAPI : /api/.*, VSCodeAdapter : /vscode/.*"
   },
   { "name": "client", "label": "Host", "query": "open-vsx.org" }
  ]
 },
 "panels": [
  {
   "title": "${uri_prefix} Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(application, client_name, instance, job, method, uri) (rate(http_client_requests_seconds_count{job=\"Open VSX Registry input\", client_name=~\"${client:value}\", uri=~\"${uri_prefix:value}\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "${uri_prefix} Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(application, client_name, instance, job, method, uri) (rate(http_client_requests_seconds_count{job=\"Open VSX Registry input\", client_name=~\"${client:value}\", uri=~\"${uri_prefix:value}\", status=~\"(4|5)..\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "${uri_prefix} Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "(sum by(application, client_name, instance, job, method, uri) (rate(http_client_requests_seconds_sum{job=\"Open VSX Registry input\", client_name=~\"${client:value}\", uri=~\"${uri_prefix:value}\"}[$__rate_interval])))/(sum by(application, client_name, instance, job, method, uri) (rate(http_client_requests_seconds_count{job=\"Open VSX Registry input\", client_name=~\"${client:value}\", uri=~\"${uri_prefix:value}\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}