/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables.records;


import org.eclipse.openvsx.jooq.tables.AdminStatisticsExtensionsByRating;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AdminStatisticsExtensionsByRatingRecord extends TableRecordImpl<AdminStatisticsExtensionsByRatingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.admin_statistics_extensions_by_rating.admin_statistics_id</code>.
     */
    public void setAdminStatisticsId(Long value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>public.admin_statistics_extensions_by_rating.admin_statistics_id</code>.
     */
    public Long getAdminStatisticsId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>public.admin_statistics_extensions_by_rating.rating</code>.
     */
    public void setRating(Integer value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.admin_statistics_extensions_by_rating.rating</code>.
     */
    public Integer getRating() {
        return (Integer) get(1);
    }

    /**
     * Setter for
     * <code>public.admin_statistics_extensions_by_rating.extensions</code>.
     */
    public void setExtensions(Integer value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>public.admin_statistics_extensions_by_rating.extensions</code>.
     */
    public Integer getExtensions() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdminStatisticsExtensionsByRatingRecord
     */
    public AdminStatisticsExtensionsByRatingRecord() {
        super(AdminStatisticsExtensionsByRating.ADMIN_STATISTICS_EXTENSIONS_BY_RATING);
    }

    /**
     * Create a detached, initialised AdminStatisticsExtensionsByRatingRecord
     */
    public AdminStatisticsExtensionsByRatingRecord(Long adminStatisticsId, Integer rating, Integer extensions) {
        super(AdminStatisticsExtensionsByRating.ADMIN_STATISTICS_EXTENSIONS_BY_RATING);

        setAdminStatisticsId(adminStatisticsId);
        setRating(rating);
        setExtensions(extensions);
        resetChangedOnNotNull();
    }
}
