/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables.records;


import org.eclipse.openvsx.jooq.tables.AdminStatisticsTopNamespaceExtensionVersions;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AdminStatisticsTopNamespaceExtensionVersionsRecord extends TableRecordImpl<AdminStatisticsTopNamespaceExtensionVersionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.admin_statistics_top_namespace_extension_versions.admin_statistics_id</code>.
     */
    public void setAdminStatisticsId(Long value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>public.admin_statistics_top_namespace_extension_versions.admin_statistics_id</code>.
     */
    public Long getAdminStatisticsId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>public.admin_statistics_top_namespace_extension_versions.namespace</code>.
     */
    public void setNamespace(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.admin_statistics_top_namespace_extension_versions.namespace</code>.
     */
    public String getNamespace() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>public.admin_statistics_top_namespace_extension_versions.extension_version_count</code>.
     */
    public void setExtensionVersionCount(Integer value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>public.admin_statistics_top_namespace_extension_versions.extension_version_count</code>.
     */
    public Integer getExtensionVersionCount() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdminStatisticsTopNamespaceExtensionVersionsRecord
     */
    public AdminStatisticsTopNamespaceExtensionVersionsRecord() {
        super(AdminStatisticsTopNamespaceExtensionVersions.ADMIN_STATISTICS_TOP_NAMESPACE_EXTENSION_VERSIONS);
    }

    /**
     * Create a detached, initialised
     * AdminStatisticsTopNamespaceExtensionVersionsRecord
     */
    public AdminStatisticsTopNamespaceExtensionVersionsRecord(Long adminStatisticsId, String namespace, Integer extensionVersionCount) {
        super(AdminStatisticsTopNamespaceExtensionVersions.ADMIN_STATISTICS_TOP_NAMESPACE_EXTENSION_VERSIONS);

        setAdminStatisticsId(adminStatisticsId);
        setNamespace(namespace);
        setExtensionVersionCount(extensionVersionCount);
        resetChangedOnNotNull();
    }
}
