/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables.records;


import java.time.LocalDateTime;

import org.eclipse.openvsx.jooq.tables.ExtensionReview;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ExtensionReviewRecord extends UpdatableRecordImpl<ExtensionReviewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.extension_review.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.extension_review.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.extension_review.active</code>.
     */
    public void setActive(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.extension_review.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>public.extension_review.comment</code>.
     */
    public void setComment(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.extension_review.comment</code>.
     */
    public String getComment() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.extension_review.rating</code>.
     */
    public void setRating(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.extension_review.rating</code>.
     */
    public Integer getRating() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.extension_review.timestamp</code>.
     */
    public void setTimestamp(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.extension_review.timestamp</code>.
     */
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.extension_review.title</code>.
     */
    public void setTitle(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.extension_review.title</code>.
     */
    public String getTitle() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.extension_review.extension_id</code>.
     */
    public void setExtensionId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.extension_review.extension_id</code>.
     */
    public Long getExtensionId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.extension_review.user_id</code>.
     */
    public void setUserId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.extension_review.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExtensionReviewRecord
     */
    public ExtensionReviewRecord() {
        super(ExtensionReview.EXTENSION_REVIEW);
    }

    /**
     * Create a detached, initialised ExtensionReviewRecord
     */
    public ExtensionReviewRecord(Long id, Boolean active, String comment, Integer rating, LocalDateTime timestamp, String title, Long extensionId, Long userId) {
        super(ExtensionReview.EXTENSION_REVIEW);

        setId(id);
        setActive(active);
        setComment(comment);
        setRating(rating);
        setTimestamp(timestamp);
        setTitle(title);
        setExtensionId(extensionId);
        setUserId(userId);
        resetChangedOnNotNull();
    }
}
