/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables.records;


import java.time.LocalDateTime;

import org.eclipse.openvsx.jooq.tables.ExtensionValidationFailure;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ExtensionValidationFailureRecord extends UpdatableRecordImpl<ExtensionValidationFailureRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.extension_validation_failure.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.extension_validation_failure.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.extension_validation_failure.scan_id</code>.
     */
    public void setScanId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.extension_validation_failure.scan_id</code>.
     */
    public Long getScanId() {
        return (Long) get(1);
    }

    /**
     * Setter for
     * <code>public.extension_validation_failure.validation_type</code>.
     */
    public void setValidationType(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>public.extension_validation_failure.validation_type</code>.
     */
    public String getValidationType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.extension_validation_failure.rule_name</code>.
     */
    public void setRuleName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.extension_validation_failure.rule_name</code>.
     */
    public String getRuleName() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>public.extension_validation_failure.validation_failure_reason</code>.
     */
    public void setValidationFailureReason(String value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>public.extension_validation_failure.validation_failure_reason</code>.
     */
    public String getValidationFailureReason() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.extension_validation_failure.enforced</code>.
     */
    public void setEnforced(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.extension_validation_failure.enforced</code>.
     */
    public Boolean getEnforced() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.extension_validation_failure.detected_at</code>.
     */
    public void setDetectedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.extension_validation_failure.detected_at</code>.
     */
    public LocalDateTime getDetectedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExtensionValidationFailureRecord
     */
    public ExtensionValidationFailureRecord() {
        super(ExtensionValidationFailure.EXTENSION_VALIDATION_FAILURE);
    }

    /**
     * Create a detached, initialised ExtensionValidationFailureRecord
     */
    public ExtensionValidationFailureRecord(Long id, Long scanId, String validationType, String ruleName, String validationFailureReason, Boolean enforced, LocalDateTime detectedAt) {
        super(ExtensionValidationFailure.EXTENSION_VALIDATION_FAILURE);

        setId(id);
        setScanId(scanId);
        setValidationType(validationType);
        setRuleName(ruleName);
        setValidationFailureReason(validationFailureReason);
        setEnforced(enforced);
        setDetectedAt(detectedAt);
        resetChangedOnNotNull();
    }
}
