/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables.records;


import java.time.LocalDateTime;

import org.eclipse.openvsx.jooq.tables.Extension;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ExtensionRecord extends UpdatableRecordImpl<ExtensionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.extension.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.extension.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.extension.average_rating</code>.
     */
    public void setAverageRating(Double value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.extension.average_rating</code>.
     */
    public Double getAverageRating() {
        return (Double) get(1);
    }

    /**
     * Setter for <code>public.extension.download_count</code>.
     */
    public void setDownloadCount(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.extension.download_count</code>.
     */
    public Integer getDownloadCount() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.extension.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.extension.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.extension.namespace_id</code>.
     */
    public void setNamespaceId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.extension.namespace_id</code>.
     */
    public Long getNamespaceId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.extension.public_id</code>.
     */
    public void setPublicId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.extension.public_id</code>.
     */
    public String getPublicId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.extension.active</code>.
     */
    public void setActive(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.extension.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.extension.published_date</code>.
     */
    public void setPublishedDate(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.extension.published_date</code>.
     */
    public LocalDateTime getPublishedDate() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.extension.last_updated_date</code>.
     */
    public void setLastUpdatedDate(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.extension.last_updated_date</code>.
     */
    public LocalDateTime getLastUpdatedDate() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>public.extension.review_count</code>.
     */
    public void setReviewCount(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.extension.review_count</code>.
     */
    public Long getReviewCount() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>public.extension.deprecated</code>.
     */
    public void setDeprecated(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.extension.deprecated</code>.
     */
    public Boolean getDeprecated() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>public.extension.replacement_id</code>.
     */
    public void setReplacementId(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.extension.replacement_id</code>.
     */
    public Long getReplacementId() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>public.extension.downloadable</code>.
     */
    public void setDownloadable(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.extension.downloadable</code>.
     */
    public Boolean getDownloadable() {
        return (Boolean) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExtensionRecord
     */
    public ExtensionRecord() {
        super(Extension.EXTENSION);
    }

    /**
     * Create a detached, initialised ExtensionRecord
     */
    public ExtensionRecord(Long id, Double averageRating, Integer downloadCount, String name, Long namespaceId, String publicId, Boolean active, LocalDateTime publishedDate, LocalDateTime lastUpdatedDate, Long reviewCount, Boolean deprecated, Long replacementId, Boolean downloadable) {
        super(Extension.EXTENSION);

        setId(id);
        setAverageRating(averageRating);
        setDownloadCount(downloadCount);
        setName(name);
        setNamespaceId(namespaceId);
        setPublicId(publicId);
        setActive(active);
        setPublishedDate(publishedDate);
        setLastUpdatedDate(lastUpdatedDate);
        setReviewCount(reviewCount);
        setDeprecated(deprecated);
        setReplacementId(replacementId);
        setDownloadable(downloadable);
        resetChangedOnNotNull();
    }
}
