/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables.records;


import java.time.LocalDateTime;

import org.eclipse.openvsx.jooq.tables.JobrunrJobs;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JobrunrJobsRecord extends UpdatableRecordImpl<JobrunrJobsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.jobrunr_jobs.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.jobrunr_jobs.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.jobrunr_jobs.version</code>.
     */
    public void setVersion(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.jobrunr_jobs.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.jobrunr_jobs.jobasjson</code>.
     */
    public void setJobasjson(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.jobrunr_jobs.jobasjson</code>.
     */
    public String getJobasjson() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.jobrunr_jobs.jobsignature</code>.
     */
    public void setJobsignature(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.jobrunr_jobs.jobsignature</code>.
     */
    public String getJobsignature() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.jobrunr_jobs.state</code>.
     */
    public void setState(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.jobrunr_jobs.state</code>.
     */
    public String getState() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.jobrunr_jobs.createdat</code>.
     */
    public void setCreatedat(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.jobrunr_jobs.createdat</code>.
     */
    public LocalDateTime getCreatedat() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.jobrunr_jobs.updatedat</code>.
     */
    public void setUpdatedat(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.jobrunr_jobs.updatedat</code>.
     */
    public LocalDateTime getUpdatedat() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.jobrunr_jobs.scheduledat</code>.
     */
    public void setScheduledat(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.jobrunr_jobs.scheduledat</code>.
     */
    public LocalDateTime getScheduledat() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.jobrunr_jobs.recurringjobid</code>.
     */
    public void setRecurringjobid(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.jobrunr_jobs.recurringjobid</code>.
     */
    public String getRecurringjobid() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JobrunrJobsRecord
     */
    public JobrunrJobsRecord() {
        super(JobrunrJobs.JOBRUNR_JOBS);
    }

    /**
     * Create a detached, initialised JobrunrJobsRecord
     */
    public JobrunrJobsRecord(String id, Integer version, String jobasjson, String jobsignature, String state, LocalDateTime createdat, LocalDateTime updatedat, LocalDateTime scheduledat, String recurringjobid) {
        super(JobrunrJobs.JOBRUNR_JOBS);

        setId(id);
        setVersion(version);
        setJobasjson(jobasjson);
        setJobsignature(jobsignature);
        setState(state);
        setCreatedat(createdat);
        setUpdatedat(updatedat);
        setScheduledat(scheduledat);
        setRecurringjobid(recurringjobid);
        resetChangedOnNotNull();
    }
}
