/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables.records;


import org.eclipse.openvsx.jooq.tables.MigrationItem;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MigrationItemRecord extends UpdatableRecordImpl<MigrationItemRecord> implements Record4<Long, String, Long, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.migration_item.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.migration_item.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.migration_item.migration_script</code>.
     */
    public void setMigrationScript(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.migration_item.migration_script</code>.
     */
    public String getMigrationScript() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.migration_item.entity_id</code>.
     */
    public void setEntityId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.migration_item.entity_id</code>.
     */
    public Long getEntityId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.migration_item.migration_scheduled</code>.
     */
    public void setMigrationScheduled(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.migration_item.migration_scheduled</code>.
     */
    public Boolean getMigrationScheduled() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, Long, Boolean> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, Long, Boolean> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return MigrationItem.MIGRATION_ITEM.ID;
    }

    @Override
    public Field<String> field2() {
        return MigrationItem.MIGRATION_ITEM.MIGRATION_SCRIPT;
    }

    @Override
    public Field<Long> field3() {
        return MigrationItem.MIGRATION_ITEM.ENTITY_ID;
    }

    @Override
    public Field<Boolean> field4() {
        return MigrationItem.MIGRATION_ITEM.MIGRATION_SCHEDULED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getMigrationScript();
    }

    @Override
    public Long component3() {
        return getEntityId();
    }

    @Override
    public Boolean component4() {
        return getMigrationScheduled();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getMigrationScript();
    }

    @Override
    public Long value3() {
        return getEntityId();
    }

    @Override
    public Boolean value4() {
        return getMigrationScheduled();
    }

    @Override
    public MigrationItemRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MigrationItemRecord value2(String value) {
        setMigrationScript(value);
        return this;
    }

    @Override
    public MigrationItemRecord value3(Long value) {
        setEntityId(value);
        return this;
    }

    @Override
    public MigrationItemRecord value4(Boolean value) {
        setMigrationScheduled(value);
        return this;
    }

    @Override
    public MigrationItemRecord values(Long value1, String value2, Long value3, Boolean value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MigrationItemRecord
     */
    public MigrationItemRecord() {
        super(MigrationItem.MIGRATION_ITEM);
    }

    /**
     * Create a detached, initialised MigrationItemRecord
     */
    public MigrationItemRecord(Long id, String migrationScript, Long entityId, Boolean migrationScheduled) {
        super(MigrationItem.MIGRATION_ITEM);

        setId(id);
        setMigrationScript(migrationScript);
        setEntityId(entityId);
        setMigrationScheduled(migrationScheduled);
    }
}
