/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables.records;


import org.eclipse.openvsx.jooq.tables.MigrationItem;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MigrationItemRecord extends UpdatableRecordImpl<MigrationItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.migration_item.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.migration_item.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.migration_item.entity_id</code>.
     */
    public void setEntityId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.migration_item.entity_id</code>.
     */
    public Long getEntityId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.migration_item.migration_scheduled</code>.
     */
    public void setMigrationScheduled(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.migration_item.migration_scheduled</code>.
     */
    public Boolean getMigrationScheduled() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.migration_item.job_name</code>.
     */
    public void setJobName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.migration_item.job_name</code>.
     */
    public String getJobName() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MigrationItemRecord
     */
    public MigrationItemRecord() {
        super(MigrationItem.MIGRATION_ITEM);
    }

    /**
     * Create a detached, initialised MigrationItemRecord
     */
    public MigrationItemRecord(Long id, Long entityId, Boolean migrationScheduled, String jobName) {
        super(MigrationItem.MIGRATION_ITEM);

        setId(id);
        setEntityId(entityId);
        setMigrationScheduled(migrationScheduled);
        setJobName(jobName);
        resetChangedOnNotNull();
    }
}
