/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables.records;


import org.eclipse.openvsx.jooq.tables.Namespace;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NamespaceRecord extends UpdatableRecordImpl<NamespaceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.namespace.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.namespace.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.namespace.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.namespace.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.namespace.public_id</code>.
     */
    public void setPublicId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.namespace.public_id</code>.
     */
    public String getPublicId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.namespace.display_name</code>.
     */
    public void setDisplayName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.namespace.display_name</code>.
     */
    public String getDisplayName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.namespace.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.namespace.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.namespace.website</code>.
     */
    public void setWebsite(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.namespace.website</code>.
     */
    public String getWebsite() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.namespace.support_link</code>.
     */
    public void setSupportLink(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.namespace.support_link</code>.
     */
    public String getSupportLink() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.namespace.logo_name</code>.
     */
    public void setLogoName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.namespace.logo_name</code>.
     */
    public String getLogoName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.namespace.logo_bytes</code>.
     */
    public void setLogoBytes(byte[] value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.namespace.logo_bytes</code>.
     */
    public byte[] getLogoBytes() {
        return (byte[]) get(8);
    }

    /**
     * Setter for <code>public.namespace.logo_storage_type</code>.
     */
    public void setLogoStorageType(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.namespace.logo_storage_type</code>.
     */
    public String getLogoStorageType() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NamespaceRecord
     */
    public NamespaceRecord() {
        super(Namespace.NAMESPACE);
    }

    /**
     * Create a detached, initialised NamespaceRecord
     */
    public NamespaceRecord(Long id, String name, String publicId, String displayName, String description, String website, String supportLink, String logoName, byte[] logoBytes, String logoStorageType) {
        super(Namespace.NAMESPACE);

        setId(id);
        setName(name);
        setPublicId(publicId);
        setDisplayName(displayName);
        setDescription(description);
        setWebsite(website);
        setSupportLink(supportLink);
        setLogoName(logoName);
        setLogoBytes(logoBytes);
        setLogoStorageType(logoStorageType);
        resetChangedOnNotNull();
    }
}
