/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables.records;


import org.eclipse.openvsx.jooq.tables.Namespace;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NamespaceRecord extends UpdatableRecordImpl<NamespaceRecord> implements Record10<Long, String, String, String, String, String, String, String, byte[], String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.namespace.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.namespace.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.namespace.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.namespace.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.namespace.public_id</code>.
     */
    public void setPublicId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.namespace.public_id</code>.
     */
    public String getPublicId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.namespace.display_name</code>.
     */
    public void setDisplayName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.namespace.display_name</code>.
     */
    public String getDisplayName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.namespace.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.namespace.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.namespace.website</code>.
     */
    public void setWebsite(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.namespace.website</code>.
     */
    public String getWebsite() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.namespace.support_link</code>.
     */
    public void setSupportLink(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.namespace.support_link</code>.
     */
    public String getSupportLink() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.namespace.logo_name</code>.
     */
    public void setLogoName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.namespace.logo_name</code>.
     */
    public String getLogoName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.namespace.logo_bytes</code>.
     */
    public void setLogoBytes(byte[] value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.namespace.logo_bytes</code>.
     */
    public byte[] getLogoBytes() {
        return (byte[]) get(8);
    }

    /**
     * Setter for <code>public.namespace.logo_storage_type</code>.
     */
    public void setLogoStorageType(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.namespace.logo_storage_type</code>.
     */
    public String getLogoStorageType() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, String, String, String, String, String, String, String, byte[], String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, String, String, String, String, String, String, String, byte[], String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Namespace.NAMESPACE.ID;
    }

    @Override
    public Field<String> field2() {
        return Namespace.NAMESPACE.NAME;
    }

    @Override
    public Field<String> field3() {
        return Namespace.NAMESPACE.PUBLIC_ID;
    }

    @Override
    public Field<String> field4() {
        return Namespace.NAMESPACE.DISPLAY_NAME;
    }

    @Override
    public Field<String> field5() {
        return Namespace.NAMESPACE.DESCRIPTION;
    }

    @Override
    public Field<String> field6() {
        return Namespace.NAMESPACE.WEBSITE;
    }

    @Override
    public Field<String> field7() {
        return Namespace.NAMESPACE.SUPPORT_LINK;
    }

    @Override
    public Field<String> field8() {
        return Namespace.NAMESPACE.LOGO_NAME;
    }

    @Override
    public Field<byte[]> field9() {
        return Namespace.NAMESPACE.LOGO_BYTES;
    }

    @Override
    public Field<String> field10() {
        return Namespace.NAMESPACE.LOGO_STORAGE_TYPE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getPublicId();
    }

    @Override
    public String component4() {
        return getDisplayName();
    }

    @Override
    public String component5() {
        return getDescription();
    }

    @Override
    public String component6() {
        return getWebsite();
    }

    @Override
    public String component7() {
        return getSupportLink();
    }

    @Override
    public String component8() {
        return getLogoName();
    }

    @Override
    public byte[] component9() {
        return getLogoBytes();
    }

    @Override
    public String component10() {
        return getLogoStorageType();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getPublicId();
    }

    @Override
    public String value4() {
        return getDisplayName();
    }

    @Override
    public String value5() {
        return getDescription();
    }

    @Override
    public String value6() {
        return getWebsite();
    }

    @Override
    public String value7() {
        return getSupportLink();
    }

    @Override
    public String value8() {
        return getLogoName();
    }

    @Override
    public byte[] value9() {
        return getLogoBytes();
    }

    @Override
    public String value10() {
        return getLogoStorageType();
    }

    @Override
    public NamespaceRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public NamespaceRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public NamespaceRecord value3(String value) {
        setPublicId(value);
        return this;
    }

    @Override
    public NamespaceRecord value4(String value) {
        setDisplayName(value);
        return this;
    }

    @Override
    public NamespaceRecord value5(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public NamespaceRecord value6(String value) {
        setWebsite(value);
        return this;
    }

    @Override
    public NamespaceRecord value7(String value) {
        setSupportLink(value);
        return this;
    }

    @Override
    public NamespaceRecord value8(String value) {
        setLogoName(value);
        return this;
    }

    @Override
    public NamespaceRecord value9(byte[] value) {
        setLogoBytes(value);
        return this;
    }

    @Override
    public NamespaceRecord value10(String value) {
        setLogoStorageType(value);
        return this;
    }

    @Override
    public NamespaceRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, byte[] value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NamespaceRecord
     */
    public NamespaceRecord() {
        super(Namespace.NAMESPACE);
    }

    /**
     * Create a detached, initialised NamespaceRecord
     */
    public NamespaceRecord(Long id, String name, String publicId, String displayName, String description, String website, String supportLink, String logoName, byte[] logoBytes, String logoStorageType) {
        super(Namespace.NAMESPACE);

        setId(id);
        setName(name);
        setPublicId(publicId);
        setDisplayName(displayName);
        setDescription(description);
        setWebsite(website);
        setSupportLink(supportLink);
        setLogoName(logoName);
        setLogoBytes(logoBytes);
        setLogoStorageType(logoStorageType);
    }
}
