/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables.records;


import org.eclipse.openvsx.jooq.tables.NamespaceSocialLinks;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NamespaceSocialLinksRecord extends TableRecordImpl<NamespaceSocialLinksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.namespace_social_links.namespace_id</code>.
     */
    public void setNamespaceId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.namespace_social_links.namespace_id</code>.
     */
    public Long getNamespaceId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.namespace_social_links.provider</code>.
     */
    public void setProvider(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.namespace_social_links.provider</code>.
     */
    public String getProvider() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.namespace_social_links.social_link</code>.
     */
    public void setSocialLink(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.namespace_social_links.social_link</code>.
     */
    public String getSocialLink() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NamespaceSocialLinksRecord
     */
    public NamespaceSocialLinksRecord() {
        super(NamespaceSocialLinks.NAMESPACE_SOCIAL_LINKS);
    }

    /**
     * Create a detached, initialised NamespaceSocialLinksRecord
     */
    public NamespaceSocialLinksRecord(Long namespaceId, String provider, String socialLink) {
        super(NamespaceSocialLinks.NAMESPACE_SOCIAL_LINKS);

        setNamespaceId(namespaceId);
        setProvider(provider);
        setSocialLink(socialLink);
        resetChangedOnNotNull();
    }
}
