/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables.records;


import java.time.LocalDateTime;

import org.eclipse.openvsx.jooq.tables.Shedlock;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShedlockRecord extends UpdatableRecordImpl<ShedlockRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.shedlock.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.shedlock.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.shedlock.lock_until</code>.
     */
    public void setLockUntil(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.shedlock.lock_until</code>.
     */
    public LocalDateTime getLockUntil() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.shedlock.locked_at</code>.
     */
    public void setLockedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.shedlock.locked_at</code>.
     */
    public LocalDateTime getLockedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.shedlock.locked_by</code>.
     */
    public void setLockedBy(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.shedlock.locked_by</code>.
     */
    public String getLockedBy() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShedlockRecord
     */
    public ShedlockRecord() {
        super(Shedlock.SHEDLOCK);
    }

    /**
     * Create a detached, initialised ShedlockRecord
     */
    public ShedlockRecord(String name, LocalDateTime lockUntil, LocalDateTime lockedAt, String lockedBy) {
        super(Shedlock.SHEDLOCK);

        setName(name);
        setLockUntil(lockUntil);
        setLockedAt(lockedAt);
        setLockedBy(lockedBy);
        resetChangedOnNotNull();
    }
}
