/******************************************************************************
 * Copyright (c) 2026 Contributors to the Eclipse Foundation.
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *****************************************************************************/

package org.eclipse.openvsx.publish;

import java.util.List;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Configuration;

import org.eclipse.openvsx.ExtensionProcessor;

@Configuration
@ConfigurationProperties("ovsx.publishing")
public class PublishingConfig {
    private static final int MAX_CONTENT_SIZE = 512 * 1024 * 1024;

    private long maxContentSize = MAX_CONTENT_SIZE;

    private boolean requireLicense;

    /**
     * Allows to specify a list of unsupported icon formats identified by their extension.
     * <p>
     * See: <a href="https://github.com/eclipse-openvsx/openvsx/issues/2">Block SVG Images</a>
     */
    private List<String> unsupportedIconFormats = List.of("svg");

    /**
     * Maximum number of tags declared by the extension author to extract from a package and store with
     * an extension version. Tags beyond that limit are dropped, a negative value keeps all of them.
     * Internal tags are not counted against this limit, see {@link #maxInternalTags}.
     * <p>
     * See: <a href="https://github.com/eclipse-openvsx/openvsx/issues/1968">Limit the number of
     * processed tags per extension</a>
     */
    private int maxTags = ExtensionProcessor.DEFAULT_MAX_TAGS;

    /**
     * Maximum number of internal tags, i.e. tags generated by the packaging tool such as
     * {@code __ext_yml}, to extract from a package and store with an extension version. Tags beyond
     * that limit are dropped, a negative value keeps all of them.
     */
    private int maxInternalTags = ExtensionProcessor.DEFAULT_MAX_INTERNAL_TAGS;

    public long getMaxContentSize() {
        return maxContentSize;
    }

    public void setMaxContentSize(int maxContentSize) {
        this.maxContentSize = maxContentSize;
    }

    public boolean isRequireLicense() {
        return requireLicense;
    }

    public void setRequireLicense(boolean requireLicense) {
        this.requireLicense = requireLicense;
    }

    public List<String> getUnsupportedIconFormats() {
        return unsupportedIconFormats;
    }

    public void setUnsupportedIconFormats(List<String> unsupportedIconFormats) {
        this.unsupportedIconFormats = unsupportedIconFormats;
    }

    public int getMaxTags() {
        return maxTags;
    }

    public void setMaxTags(int maxTags) {
        this.maxTags = maxTags;
    }

    public int getMaxInternalTags() {
        return maxInternalTags;
    }

    public void setMaxInternalTags(int maxInternalTags) {
        this.maxInternalTags = maxInternalTags;
    }
}
