/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.eclipse.openvsx.jooq.Indexes;
import org.eclipse.openvsx.jooq.Keys;
import org.eclipse.openvsx.jooq.Public;
import org.eclipse.openvsx.jooq.tables.records.AdminScanDecisionRecord;
import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AdminScanDecision extends TableImpl<AdminScanDecisionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.admin_scan_decision</code>
     */
    public static final AdminScanDecision ADMIN_SCAN_DECISION = new AdminScanDecision();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AdminScanDecisionRecord> getRecordType() {
        return AdminScanDecisionRecord.class;
    }

    /**
     * The column <code>public.admin_scan_decision.id</code>.
     */
    public final TableField<AdminScanDecisionRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.admin_scan_decision.scan_id</code>.
     */
    public final TableField<AdminScanDecisionRecord, Long> SCAN_ID = createField(DSL.name("scan_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.admin_scan_decision.decision</code>.
     */
    public final TableField<AdminScanDecisionRecord, String> DECISION = createField(DSL.name("decision"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.admin_scan_decision.decided_by_id</code>.
     */
    public final TableField<AdminScanDecisionRecord, Long> DECIDED_BY_ID = createField(DSL.name("decided_by_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.admin_scan_decision.decided_at</code>.
     */
    public final TableField<AdminScanDecisionRecord, LocalDateTime> DECIDED_AT = createField(DSL.name("decided_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private AdminScanDecision(Name alias, Table<AdminScanDecisionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AdminScanDecision(Name alias, Table<AdminScanDecisionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.admin_scan_decision</code> table reference
     */
    public AdminScanDecision(String alias) {
        this(DSL.name(alias), ADMIN_SCAN_DECISION);
    }

    /**
     * Create an aliased <code>public.admin_scan_decision</code> table reference
     */
    public AdminScanDecision(Name alias) {
        this(alias, ADMIN_SCAN_DECISION);
    }

    /**
     * Create a <code>public.admin_scan_decision</code> table reference
     */
    public AdminScanDecision() {
        this(DSL.name("admin_scan_decision"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_SCAN_DECISION_DECIDED_AT, Indexes.IDX_SCAN_DECISION_DECIDED_BY, Indexes.IDX_SCAN_DECISION_DECISION);
    }

    @Override
    public Identity<AdminScanDecisionRecord, Long> getIdentity() {
        return (Identity<AdminScanDecisionRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AdminScanDecisionRecord> getPrimaryKey() {
        return Keys.ADMIN_SCAN_DECISION_PKEY;
    }

    @Override
    public List<UniqueKey<AdminScanDecisionRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.ADMIN_SCAN_DECISION_SCAN_ID_KEY);
    }

    @Override
    public List<ForeignKey<AdminScanDecisionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ADMIN_SCAN_DECISION__FK_ADMIN_SCAN_DECISION_USER, Keys.ADMIN_SCAN_DECISION__FK_DECISION_SCAN);
    }

    @Override
    public List<Check<AdminScanDecisionRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("chk_decision_value"), "(((decision)::text = ANY ((ARRAY['ALLOWED'::character varying, 'BLOCKED'::character varying])::text[])))", true)
        );
    }

    @Override
    public AdminScanDecision as(String alias) {
        return new AdminScanDecision(DSL.name(alias), this);
    }

    @Override
    public AdminScanDecision as(Name alias) {
        return new AdminScanDecision(alias, this);
    }

    @Override
    public AdminScanDecision as(Table<?> alias) {
        return new AdminScanDecision(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AdminScanDecision rename(String name) {
        return new AdminScanDecision(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AdminScanDecision rename(Name name) {
        return new AdminScanDecision(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AdminScanDecision rename(Table<?> name) {
        return new AdminScanDecision(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AdminScanDecision where(Condition condition) {
        return new AdminScanDecision(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AdminScanDecision where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AdminScanDecision where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AdminScanDecision where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AdminScanDecision where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AdminScanDecision where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AdminScanDecision where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AdminScanDecision where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AdminScanDecision whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AdminScanDecision whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
