/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.eclipse.openvsx.jooq.Keys;
import org.eclipse.openvsx.jooq.Public;
import org.eclipse.openvsx.jooq.tables.records.AdminStatisticsPublishersByExtensionsPublishedRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AdminStatisticsPublishersByExtensionsPublished extends TableImpl<AdminStatisticsPublishersByExtensionsPublishedRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.admin_statistics_publishers_by_extensions_published</code>
     */
    public static final AdminStatisticsPublishersByExtensionsPublished ADMIN_STATISTICS_PUBLISHERS_BY_EXTENSIONS_PUBLISHED = new AdminStatisticsPublishersByExtensionsPublished();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AdminStatisticsPublishersByExtensionsPublishedRecord> getRecordType() {
        return AdminStatisticsPublishersByExtensionsPublishedRecord.class;
    }

    /**
     * The column
     * <code>public.admin_statistics_publishers_by_extensions_published.admin_statistics_id</code>.
     */
    public final TableField<AdminStatisticsPublishersByExtensionsPublishedRecord, Long> ADMIN_STATISTICS_ID = createField(DSL.name("admin_statistics_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column
     * <code>public.admin_statistics_publishers_by_extensions_published.extensions_published</code>.
     */
    public final TableField<AdminStatisticsPublishersByExtensionsPublishedRecord, Integer> EXTENSIONS_PUBLISHED = createField(DSL.name("extensions_published"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column
     * <code>public.admin_statistics_publishers_by_extensions_published.publishers</code>.
     */
    public final TableField<AdminStatisticsPublishersByExtensionsPublishedRecord, Integer> PUBLISHERS = createField(DSL.name("publishers"), SQLDataType.INTEGER.nullable(false), this, "");

    private AdminStatisticsPublishersByExtensionsPublished(Name alias, Table<AdminStatisticsPublishersByExtensionsPublishedRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AdminStatisticsPublishersByExtensionsPublished(Name alias, Table<AdminStatisticsPublishersByExtensionsPublishedRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased
     * <code>public.admin_statistics_publishers_by_extensions_published</code>
     * table reference
     */
    public AdminStatisticsPublishersByExtensionsPublished(String alias) {
        this(DSL.name(alias), ADMIN_STATISTICS_PUBLISHERS_BY_EXTENSIONS_PUBLISHED);
    }

    /**
     * Create an aliased
     * <code>public.admin_statistics_publishers_by_extensions_published</code>
     * table reference
     */
    public AdminStatisticsPublishersByExtensionsPublished(Name alias) {
        this(alias, ADMIN_STATISTICS_PUBLISHERS_BY_EXTENSIONS_PUBLISHED);
    }

    /**
     * Create a
     * <code>public.admin_statistics_publishers_by_extensions_published</code>
     * table reference
     */
    public AdminStatisticsPublishersByExtensionsPublished() {
        this(DSL.name("admin_statistics_publishers_by_extensions_published"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<ForeignKey<AdminStatisticsPublishersByExtensionsPublishedRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ADMIN_STATISTICS_PUBLISHERS_BY_EXTENSIONS_PUBLISHED__ADMIN_STATISTICS_PUBLISHERS_BY_EXTENSIONS_PUBLISHED_FKEY);
    }

    @Override
    public AdminStatisticsPublishersByExtensionsPublished as(String alias) {
        return new AdminStatisticsPublishersByExtensionsPublished(DSL.name(alias), this);
    }

    @Override
    public AdminStatisticsPublishersByExtensionsPublished as(Name alias) {
        return new AdminStatisticsPublishersByExtensionsPublished(alias, this);
    }

    @Override
    public AdminStatisticsPublishersByExtensionsPublished as(Table<?> alias) {
        return new AdminStatisticsPublishersByExtensionsPublished(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AdminStatisticsPublishersByExtensionsPublished rename(String name) {
        return new AdminStatisticsPublishersByExtensionsPublished(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AdminStatisticsPublishersByExtensionsPublished rename(Name name) {
        return new AdminStatisticsPublishersByExtensionsPublished(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AdminStatisticsPublishersByExtensionsPublished rename(Table<?> name) {
        return new AdminStatisticsPublishersByExtensionsPublished(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AdminStatisticsPublishersByExtensionsPublished where(Condition condition) {
        return new AdminStatisticsPublishersByExtensionsPublished(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AdminStatisticsPublishersByExtensionsPublished where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AdminStatisticsPublishersByExtensionsPublished where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AdminStatisticsPublishersByExtensionsPublished where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AdminStatisticsPublishersByExtensionsPublished where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AdminStatisticsPublishersByExtensionsPublished where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AdminStatisticsPublishersByExtensionsPublished where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AdminStatisticsPublishersByExtensionsPublished where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AdminStatisticsPublishersByExtensionsPublished whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AdminStatisticsPublishersByExtensionsPublished whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
