/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables;


import java.util.Arrays;
import java.util.List;

import org.eclipse.openvsx.jooq.Keys;
import org.eclipse.openvsx.jooq.Public;
import org.eclipse.openvsx.jooq.tables.records.AdminStatisticsPublishersByExtensionsPublishedRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdminStatisticsPublishersByExtensionsPublished extends TableImpl<AdminStatisticsPublishersByExtensionsPublishedRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.admin_statistics_publishers_by_extensions_published</code>
     */
    public static final AdminStatisticsPublishersByExtensionsPublished ADMIN_STATISTICS_PUBLISHERS_BY_EXTENSIONS_PUBLISHED = new AdminStatisticsPublishersByExtensionsPublished();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AdminStatisticsPublishersByExtensionsPublishedRecord> getRecordType() {
        return AdminStatisticsPublishersByExtensionsPublishedRecord.class;
    }

    /**
     * The column <code>public.admin_statistics_publishers_by_extensions_published.admin_statistics_id</code>.
     */
    public final TableField<AdminStatisticsPublishersByExtensionsPublishedRecord, Long> ADMIN_STATISTICS_ID = createField(DSL.name("admin_statistics_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.admin_statistics_publishers_by_extensions_published.extensions_published</code>.
     */
    public final TableField<AdminStatisticsPublishersByExtensionsPublishedRecord, Integer> EXTENSIONS_PUBLISHED = createField(DSL.name("extensions_published"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.admin_statistics_publishers_by_extensions_published.publishers</code>.
     */
    public final TableField<AdminStatisticsPublishersByExtensionsPublishedRecord, Integer> PUBLISHERS = createField(DSL.name("publishers"), SQLDataType.INTEGER.nullable(false), this, "");

    private AdminStatisticsPublishersByExtensionsPublished(Name alias, Table<AdminStatisticsPublishersByExtensionsPublishedRecord> aliased) {
        this(alias, aliased, null);
    }

    private AdminStatisticsPublishersByExtensionsPublished(Name alias, Table<AdminStatisticsPublishersByExtensionsPublishedRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.admin_statistics_publishers_by_extensions_published</code> table reference
     */
    public AdminStatisticsPublishersByExtensionsPublished(String alias) {
        this(DSL.name(alias), ADMIN_STATISTICS_PUBLISHERS_BY_EXTENSIONS_PUBLISHED);
    }

    /**
     * Create an aliased <code>public.admin_statistics_publishers_by_extensions_published</code> table reference
     */
    public AdminStatisticsPublishersByExtensionsPublished(Name alias) {
        this(alias, ADMIN_STATISTICS_PUBLISHERS_BY_EXTENSIONS_PUBLISHED);
    }

    /**
     * Create a <code>public.admin_statistics_publishers_by_extensions_published</code> table reference
     */
    public AdminStatisticsPublishersByExtensionsPublished() {
        this(DSL.name("admin_statistics_publishers_by_extensions_published"), null);
    }

    public <O extends Record> AdminStatisticsPublishersByExtensionsPublished(Table<O> child, ForeignKey<O, AdminStatisticsPublishersByExtensionsPublishedRecord> key) {
        super(child, key, ADMIN_STATISTICS_PUBLISHERS_BY_EXTENSIONS_PUBLISHED);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<ForeignKey<AdminStatisticsPublishersByExtensionsPublishedRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AdminStatisticsPublishersByExtensionsPublishedRecord, ?>>asList(Keys.ADMIN_STATISTICS_PUBLISHERS_BY_EXTENSIONS_PUBLISHED__ADMIN_STATISTICS_PUBLISHERS_BY_EXTENSIONS_PUBLISHED_FKEY);
    }

    private transient AdminStatistics _adminStatistics;

    public AdminStatistics adminStatistics() {
        if (_adminStatistics == null)
            _adminStatistics = new AdminStatistics(this, Keys.ADMIN_STATISTICS_PUBLISHERS_BY_EXTENSIONS_PUBLISHED__ADMIN_STATISTICS_PUBLISHERS_BY_EXTENSIONS_PUBLISHED_FKEY);

        return _adminStatistics;
    }

    @Override
    public AdminStatisticsPublishersByExtensionsPublished as(String alias) {
        return new AdminStatisticsPublishersByExtensionsPublished(DSL.name(alias), this);
    }

    @Override
    public AdminStatisticsPublishersByExtensionsPublished as(Name alias) {
        return new AdminStatisticsPublishersByExtensionsPublished(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AdminStatisticsPublishersByExtensionsPublished rename(String name) {
        return new AdminStatisticsPublishersByExtensionsPublished(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AdminStatisticsPublishersByExtensionsPublished rename(Name name) {
        return new AdminStatisticsPublishersByExtensionsPublished(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
