/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Collection;

import org.eclipse.openvsx.jooq.Public;
import org.eclipse.openvsx.jooq.tables.records.DownloadStatsDailyRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DownloadStatsDaily extends TableImpl<DownloadStatsDailyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.download_stats_daily</code>
     */
    public static final DownloadStatsDaily DOWNLOAD_STATS_DAILY = new DownloadStatsDaily();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DownloadStatsDailyRecord> getRecordType() {
        return DownloadStatsDailyRecord.class;
    }

    /**
     * The column <code>public.download_stats_daily.day</code>.
     */
    public final TableField<DownloadStatsDailyRecord, OffsetDateTime> DAY = createField(DSL.name("day"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.download_stats_daily.extension_id</code>.
     */
    public final TableField<DownloadStatsDailyRecord, Long> EXTENSION_ID = createField(DSL.name("extension_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.download_stats_daily.extension_version_id</code>.
     */
    public final TableField<DownloadStatsDailyRecord, Long> EXTENSION_VERSION_ID = createField(DSL.name("extension_version_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.download_stats_daily.version</code>.
     */
    public final TableField<DownloadStatsDailyRecord, String> VERSION = createField(DSL.name("version"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.download_stats_daily.target_platform</code>.
     */
    public final TableField<DownloadStatsDailyRecord, String> TARGET_PLATFORM = createField(DSL.name("target_platform"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.download_stats_daily.country</code>.
     */
    public final TableField<DownloadStatsDailyRecord, String> COUNTRY = createField(DSL.name("country"), SQLDataType.CHAR(2), this, "");

    /**
     * The column <code>public.download_stats_daily.downloads</code>.
     */
    public final TableField<DownloadStatsDailyRecord, Long> DOWNLOADS = createField(DSL.name("downloads"), SQLDataType.BIGINT, this, "");

    private DownloadStatsDaily(Name alias, Table<DownloadStatsDailyRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DownloadStatsDaily(Name alias, Table<DownloadStatsDailyRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("""
         create view "download_stats_daily" as  SELECT _materialized_hypertable_2.day,
            _materialized_hypertable_2.extension_id,
            _materialized_hypertable_2.extension_version_id,
            _materialized_hypertable_2.version,
            _materialized_hypertable_2.target_platform,
            _materialized_hypertable_2.country,
            _materialized_hypertable_2.downloads
           FROM _timescaledb_internal._materialized_hypertable_2
          WHERE (_materialized_hypertable_2.day < COALESCE(_timescaledb_functions.to_timestamp(_timescaledb_functions.cagg_watermark(2)), '-infinity'::timestamp with time zone))
        UNION ALL
         SELECT time_bucket('1 day'::interval, download_event."time") AS day,
            download_event.extension_id,
            download_event.extension_version_id,
            download_event.version,
            download_event.target_platform,
            download_event.country,
            sum(download_event.count) AS downloads
           FROM download_event
          WHERE (download_event."time" >= COALESCE(_timescaledb_functions.to_timestamp(_timescaledb_functions.cagg_watermark(2)), '-infinity'::timestamp with time zone))
          GROUP BY (time_bucket('1 day'::interval, download_event."time")), download_event.extension_id, download_event.extension_version_id, download_event.version, download_event.target_platform, download_event.country;
        """), where);
    }

    /**
     * Create an aliased <code>public.download_stats_daily</code> table
     * reference
     */
    public DownloadStatsDaily(String alias) {
        this(DSL.name(alias), DOWNLOAD_STATS_DAILY);
    }

    /**
     * Create an aliased <code>public.download_stats_daily</code> table
     * reference
     */
    public DownloadStatsDaily(Name alias) {
        this(alias, DOWNLOAD_STATS_DAILY);
    }

    /**
     * Create a <code>public.download_stats_daily</code> table reference
     */
    public DownloadStatsDaily() {
        this(DSL.name("download_stats_daily"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public DownloadStatsDaily as(String alias) {
        return new DownloadStatsDaily(DSL.name(alias), this);
    }

    @Override
    public DownloadStatsDaily as(Name alias) {
        return new DownloadStatsDaily(alias, this);
    }

    @Override
    public DownloadStatsDaily as(Table<?> alias) {
        return new DownloadStatsDaily(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DownloadStatsDaily rename(String name) {
        return new DownloadStatsDaily(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DownloadStatsDaily rename(Name name) {
        return new DownloadStatsDaily(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DownloadStatsDaily rename(Table<?> name) {
        return new DownloadStatsDaily(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DownloadStatsDaily where(Condition condition) {
        return new DownloadStatsDaily(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DownloadStatsDaily where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DownloadStatsDaily where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DownloadStatsDaily where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DownloadStatsDaily where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DownloadStatsDaily where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DownloadStatsDaily where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DownloadStatsDaily where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DownloadStatsDaily whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DownloadStatsDaily whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
