/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.eclipse.openvsx.jooq.Indexes;
import org.eclipse.openvsx.jooq.Keys;
import org.eclipse.openvsx.jooq.Public;
import org.eclipse.openvsx.jooq.tables.records.ExtensionReviewRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ExtensionReview extends TableImpl<ExtensionReviewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.extension_review</code>
     */
    public static final ExtensionReview EXTENSION_REVIEW = new ExtensionReview();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ExtensionReviewRecord> getRecordType() {
        return ExtensionReviewRecord.class;
    }

    /**
     * The column <code>public.extension_review.id</code>.
     */
    public final TableField<ExtensionReviewRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.extension_review.active</code>.
     */
    public final TableField<ExtensionReviewRecord, Boolean> ACTIVE = createField(DSL.name("active"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.extension_review.comment</code>.
     */
    public final TableField<ExtensionReviewRecord, String> COMMENT = createField(DSL.name("comment"), SQLDataType.VARCHAR(2048), this, "");

    /**
     * The column <code>public.extension_review.rating</code>.
     */
    public final TableField<ExtensionReviewRecord, Integer> RATING = createField(DSL.name("rating"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.extension_review.timestamp</code>.
     */
    public final TableField<ExtensionReviewRecord, LocalDateTime> TIMESTAMP = createField(DSL.name("timestamp"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.extension_review.title</code>.
     */
    public final TableField<ExtensionReviewRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.extension_review.extension_id</code>.
     */
    public final TableField<ExtensionReviewRecord, Long> EXTENSION_ID = createField(DSL.name("extension_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.extension_review.user_id</code>.
     */
    public final TableField<ExtensionReviewRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT, this, "");

    private ExtensionReview(Name alias, Table<ExtensionReviewRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ExtensionReview(Name alias, Table<ExtensionReviewRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.extension_review</code> table reference
     */
    public ExtensionReview(String alias) {
        this(DSL.name(alias), EXTENSION_REVIEW);
    }

    /**
     * Create an aliased <code>public.extension_review</code> table reference
     */
    public ExtensionReview(Name alias) {
        this(alias, EXTENSION_REVIEW);
    }

    /**
     * Create a <code>public.extension_review</code> table reference
     */
    public ExtensionReview() {
        this(DSL.name("extension_review"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.EXTENSION_REVIEW__EXTENSION_ID__IDX, Indexes.EXTENSION_REVIEW__USER_ID__IDX);
    }

    @Override
    public UniqueKey<ExtensionReviewRecord> getPrimaryKey() {
        return Keys.EXTENSION_REVIEW_PKEY;
    }

    @Override
    public List<ForeignKey<ExtensionReviewRecord, ?>> getReferences() {
        return Arrays.asList(Keys.EXTENSION_REVIEW__FKGD2DQDC23OGBNOBX8AFJFPNKP, Keys.EXTENSION_REVIEW__FKINJBN9GRK135Y6IK0UT4UJP0W);
    }

    @Override
    public ExtensionReview as(String alias) {
        return new ExtensionReview(DSL.name(alias), this);
    }

    @Override
    public ExtensionReview as(Name alias) {
        return new ExtensionReview(alias, this);
    }

    @Override
    public ExtensionReview as(Table<?> alias) {
        return new ExtensionReview(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ExtensionReview rename(String name) {
        return new ExtensionReview(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ExtensionReview rename(Name name) {
        return new ExtensionReview(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ExtensionReview rename(Table<?> name) {
        return new ExtensionReview(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ExtensionReview where(Condition condition) {
        return new ExtensionReview(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ExtensionReview where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ExtensionReview where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ExtensionReview where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ExtensionReview where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ExtensionReview where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ExtensionReview where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ExtensionReview where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ExtensionReview whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ExtensionReview whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
