/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.eclipse.openvsx.jooq.Indexes;
import org.eclipse.openvsx.jooq.Keys;
import org.eclipse.openvsx.jooq.Public;
import org.eclipse.openvsx.jooq.tables.records.ExtensionThreatRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ExtensionThreat extends TableImpl<ExtensionThreatRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.extension_threat</code>
     */
    public static final ExtensionThreat EXTENSION_THREAT = new ExtensionThreat();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ExtensionThreatRecord> getRecordType() {
        return ExtensionThreatRecord.class;
    }

    /**
     * The column <code>public.extension_threat.id</code>.
     */
    public final TableField<ExtensionThreatRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.extension_threat.scan_id</code>.
     */
    public final TableField<ExtensionThreatRecord, Long> SCAN_ID = createField(DSL.name("scan_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.extension_threat.file_name</code>.
     */
    public final TableField<ExtensionThreatRecord, String> FILE_NAME = createField(DSL.name("file_name"), SQLDataType.VARCHAR(1024), this, "");

    /**
     * The column <code>public.extension_threat.file_hash</code>.
     */
    public final TableField<ExtensionThreatRecord, String> FILE_HASH = createField(DSL.name("file_hash"), SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>public.extension_threat.file_extension</code>.
     */
    public final TableField<ExtensionThreatRecord, String> FILE_EXTENSION = createField(DSL.name("file_extension"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.extension_threat.scanner_type</code>.
     */
    public final TableField<ExtensionThreatRecord, String> SCANNER_TYPE = createField(DSL.name("scanner_type"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.extension_threat.rule_name</code>.
     */
    public final TableField<ExtensionThreatRecord, String> RULE_NAME = createField(DSL.name("rule_name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.extension_threat.reason</code>.
     */
    public final TableField<ExtensionThreatRecord, String> REASON = createField(DSL.name("reason"), SQLDataType.VARCHAR(2048), this, "");

    /**
     * The column <code>public.extension_threat.severity</code>.
     */
    public final TableField<ExtensionThreatRecord, String> SEVERITY = createField(DSL.name("severity"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.extension_threat.enforced</code>.
     */
    public final TableField<ExtensionThreatRecord, Boolean> ENFORCED = createField(DSL.name("enforced"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.extension_threat.detected_at</code>.
     */
    public final TableField<ExtensionThreatRecord, LocalDateTime> DETECTED_AT = createField(DSL.name("detected_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.extension_threat.job_id</code>.
     */
    public final TableField<ExtensionThreatRecord, Long> JOB_ID = createField(DSL.name("job_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    private ExtensionThreat(Name alias, Table<ExtensionThreatRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ExtensionThreat(Name alias, Table<ExtensionThreatRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.extension_threat</code> table reference
     */
    public ExtensionThreat(String alias) {
        this(DSL.name(alias), EXTENSION_THREAT);
    }

    /**
     * Create an aliased <code>public.extension_threat</code> table reference
     */
    public ExtensionThreat(Name alias) {
        this(alias, EXTENSION_THREAT);
    }

    /**
     * Create a <code>public.extension_threat</code> table reference
     */
    public ExtensionThreat() {
        this(DSL.name("extension_threat"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_THREAT_DETECTED_AT, Indexes.IDX_THREAT_FILE_HASH, Indexes.IDX_THREAT_JOB_ID, Indexes.IDX_THREAT_SCAN, Indexes.IDX_THREAT_SCANNER_TYPE);
    }

    @Override
    public Identity<ExtensionThreatRecord, Long> getIdentity() {
        return (Identity<ExtensionThreatRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ExtensionThreatRecord> getPrimaryKey() {
        return Keys.EXTENSION_THREAT_PKEY;
    }

    @Override
    public List<ForeignKey<ExtensionThreatRecord, ?>> getReferences() {
        return Arrays.asList(Keys.EXTENSION_THREAT__FK_THREAT_SCAN);
    }

    @Override
    public ExtensionThreat as(String alias) {
        return new ExtensionThreat(DSL.name(alias), this);
    }

    @Override
    public ExtensionThreat as(Name alias) {
        return new ExtensionThreat(alias, this);
    }

    @Override
    public ExtensionThreat as(Table<?> alias) {
        return new ExtensionThreat(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ExtensionThreat rename(String name) {
        return new ExtensionThreat(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ExtensionThreat rename(Name name) {
        return new ExtensionThreat(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ExtensionThreat rename(Table<?> name) {
        return new ExtensionThreat(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ExtensionThreat where(Condition condition) {
        return new ExtensionThreat(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ExtensionThreat where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ExtensionThreat where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ExtensionThreat where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ExtensionThreat where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ExtensionThreat where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ExtensionThreat where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ExtensionThreat where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ExtensionThreat whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ExtensionThreat whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
