/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.eclipse.openvsx.jooq.Indexes;
import org.eclipse.openvsx.jooq.Keys;
import org.eclipse.openvsx.jooq.Public;
import org.eclipse.openvsx.jooq.tables.records.ExtensionScanRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ExtensionScan extends TableImpl<ExtensionScanRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.extension_scan</code>
     */
    public static final ExtensionScan EXTENSION_SCAN = new ExtensionScan();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ExtensionScanRecord> getRecordType() {
        return ExtensionScanRecord.class;
    }

    /**
     * The column <code>public.extension_scan.id</code>.
     */
    public final TableField<ExtensionScanRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.extension_scan.namespace_name</code>.
     */
    public final TableField<ExtensionScanRecord, String> NAMESPACE_NAME = createField(DSL.name("namespace_name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.extension_scan.extension_name</code>.
     */
    public final TableField<ExtensionScanRecord, String> EXTENSION_NAME = createField(DSL.name("extension_name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.extension_scan.extension_version</code>.
     */
    public final TableField<ExtensionScanRecord, String> EXTENSION_VERSION = createField(DSL.name("extension_version"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.extension_scan.target_platform</code>.
     */
    public final TableField<ExtensionScanRecord, String> TARGET_PLATFORM = createField(DSL.name("target_platform"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.extension_scan.extension_display_name</code>.
     */
    public final TableField<ExtensionScanRecord, String> EXTENSION_DISPLAY_NAME = createField(DSL.name("extension_display_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.extension_scan.universal_target_platform</code>.
     */
    public final TableField<ExtensionScanRecord, Boolean> UNIVERSAL_TARGET_PLATFORM = createField(DSL.name("universal_target_platform"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.extension_scan.publisher</code>.
     */
    public final TableField<ExtensionScanRecord, String> PUBLISHER = createField(DSL.name("publisher"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.extension_scan.publisher_url</code>.
     */
    public final TableField<ExtensionScanRecord, String> PUBLISHER_URL = createField(DSL.name("publisher_url"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.extension_scan.started_at</code>.
     */
    public final TableField<ExtensionScanRecord, LocalDateTime> STARTED_AT = createField(DSL.name("started_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.extension_scan.completed_at</code>.
     */
    public final TableField<ExtensionScanRecord, LocalDateTime> COMPLETED_AT = createField(DSL.name("completed_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.extension_scan.status</code>.
     */
    public final TableField<ExtensionScanRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.extension_scan.error_message</code>.
     */
    public final TableField<ExtensionScanRecord, String> ERROR_MESSAGE = createField(DSL.name("error_message"), SQLDataType.VARCHAR(2048), this, "");

    private ExtensionScan(Name alias, Table<ExtensionScanRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ExtensionScan(Name alias, Table<ExtensionScanRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.extension_scan</code> table reference
     */
    public ExtensionScan(String alias) {
        this(DSL.name(alias), EXTENSION_SCAN);
    }

    /**
     * Create an aliased <code>public.extension_scan</code> table reference
     */
    public ExtensionScan(Name alias) {
        this(alias, EXTENSION_SCAN);
    }

    /**
     * Create a <code>public.extension_scan</code> table reference
     */
    public ExtensionScan() {
        this(DSL.name("extension_scan"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_EXTENSION_SCAN_COMPLETED_AT, Indexes.IDX_EXTENSION_SCAN_STARTED_AT, Indexes.IDX_EXTENSION_SCAN_STATUS, Indexes.IDX_EXTENSION_SCAN_VERSION);
    }

    @Override
    public Identity<ExtensionScanRecord, Long> getIdentity() {
        return (Identity<ExtensionScanRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ExtensionScanRecord> getPrimaryKey() {
        return Keys.EXTENSION_SCAN_PKEY;
    }

    @Override
    public ExtensionScan as(String alias) {
        return new ExtensionScan(DSL.name(alias), this);
    }

    @Override
    public ExtensionScan as(Name alias) {
        return new ExtensionScan(alias, this);
    }

    @Override
    public ExtensionScan as(Table<?> alias) {
        return new ExtensionScan(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ExtensionScan rename(String name) {
        return new ExtensionScan(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ExtensionScan rename(Name name) {
        return new ExtensionScan(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ExtensionScan rename(Table<?> name) {
        return new ExtensionScan(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ExtensionScan where(Condition condition) {
        return new ExtensionScan(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ExtensionScan where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ExtensionScan where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ExtensionScan where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ExtensionScan where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ExtensionScan where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ExtensionScan where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ExtensionScan where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ExtensionScan whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ExtensionScan whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
