/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.eclipse.openvsx.jooq.Indexes;
import org.eclipse.openvsx.jooq.Keys;
import org.eclipse.openvsx.jooq.Public;
import org.eclipse.openvsx.jooq.tables.records.FileResourceRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FileResource extends TableImpl<FileResourceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.file_resource</code>
     */
    public static final FileResource FILE_RESOURCE = new FileResource();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FileResourceRecord> getRecordType() {
        return FileResourceRecord.class;
    }

    /**
     * The column <code>public.file_resource.id</code>.
     */
    public final TableField<FileResourceRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.file_resource.type</code>.
     */
    public final TableField<FileResourceRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>public.file_resource.content</code>.
     */
    public final TableField<FileResourceRecord, byte[]> CONTENT = createField(DSL.name("content"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>public.file_resource.extension_id</code>.
     */
    public final TableField<FileResourceRecord, Long> EXTENSION_ID = createField(DSL.name("extension_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.file_resource.name</code>.
     */
    public final TableField<FileResourceRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.file_resource.storage_type</code>.
     */
    public final TableField<FileResourceRecord, String> STORAGE_TYPE = createField(DSL.name("storage_type"), SQLDataType.VARCHAR(32), this, "");

    private FileResource(Name alias, Table<FileResourceRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FileResource(Name alias, Table<FileResourceRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.file_resource</code> table reference
     */
    public FileResource(String alias) {
        this(DSL.name(alias), FILE_RESOURCE);
    }

    /**
     * Create an aliased <code>public.file_resource</code> table reference
     */
    public FileResource(Name alias) {
        this(alias, FILE_RESOURCE);
    }

    /**
     * Create a <code>public.file_resource</code> table reference
     */
    public FileResource() {
        this(DSL.name("file_resource"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.FILE_RESOURCE_EXTENSION_IDX, Indexes.FILE_RESOURCE_TYPE_IDX);
    }

    @Override
    public UniqueKey<FileResourceRecord> getPrimaryKey() {
        return Keys.FILE_RESOURCE_PKEY;
    }

    @Override
    public List<ForeignKey<FileResourceRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FILE_RESOURCE__FILE_RESOURCE_EXTENSION_FKEY);
    }

    @Override
    public FileResource as(String alias) {
        return new FileResource(DSL.name(alias), this);
    }

    @Override
    public FileResource as(Name alias) {
        return new FileResource(alias, this);
    }

    @Override
    public FileResource as(Table<?> alias) {
        return new FileResource(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FileResource rename(String name) {
        return new FileResource(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FileResource rename(Name name) {
        return new FileResource(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FileResource rename(Table<?> name) {
        return new FileResource(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FileResource where(Condition condition) {
        return new FileResource(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FileResource where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FileResource where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FileResource where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FileResource where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FileResource where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FileResource where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FileResource where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FileResource whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FileResource whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
