/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.eclipse.openvsx.jooq.Indexes;
import org.eclipse.openvsx.jooq.Keys;
import org.eclipse.openvsx.jooq.Public;
import org.eclipse.openvsx.jooq.tables.records.JobrunrRecurringJobsRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JobrunrRecurringJobs extends TableImpl<JobrunrRecurringJobsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.jobrunr_recurring_jobs</code>
     */
    public static final JobrunrRecurringJobs JOBRUNR_RECURRING_JOBS = new JobrunrRecurringJobs();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JobrunrRecurringJobsRecord> getRecordType() {
        return JobrunrRecurringJobsRecord.class;
    }

    /**
     * The column <code>public.jobrunr_recurring_jobs.id</code>.
     */
    public final TableField<JobrunrRecurringJobsRecord, String> ID = createField(DSL.name("id"), SQLDataType.CHAR(128).nullable(false), this, "");

    /**
     * The column <code>public.jobrunr_recurring_jobs.version</code>.
     */
    public final TableField<JobrunrRecurringJobsRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.jobrunr_recurring_jobs.jobasjson</code>.
     */
    public final TableField<JobrunrRecurringJobsRecord, String> JOBASJSON = createField(DSL.name("jobasjson"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.jobrunr_recurring_jobs.createdat</code>.
     */
    public final TableField<JobrunrRecurringJobsRecord, Long> CREATEDAT = createField(DSL.name("createdat"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("'0'::bigint"), SQLDataType.BIGINT)), this, "");

    private JobrunrRecurringJobs(Name alias, Table<JobrunrRecurringJobsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private JobrunrRecurringJobs(Name alias, Table<JobrunrRecurringJobsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.jobrunr_recurring_jobs</code> table
     * reference
     */
    public JobrunrRecurringJobs(String alias) {
        this(DSL.name(alias), JOBRUNR_RECURRING_JOBS);
    }

    /**
     * Create an aliased <code>public.jobrunr_recurring_jobs</code> table
     * reference
     */
    public JobrunrRecurringJobs(Name alias) {
        this(alias, JOBRUNR_RECURRING_JOBS);
    }

    /**
     * Create a <code>public.jobrunr_recurring_jobs</code> table reference
     */
    public JobrunrRecurringJobs() {
        this(DSL.name("jobrunr_recurring_jobs"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.JOBRUNR_RECURRING_JOB_CREATED_AT_IDX);
    }

    @Override
    public UniqueKey<JobrunrRecurringJobsRecord> getPrimaryKey() {
        return Keys.JOBRUNR_RECURRING_JOBS_PKEY;
    }

    @Override
    public JobrunrRecurringJobs as(String alias) {
        return new JobrunrRecurringJobs(DSL.name(alias), this);
    }

    @Override
    public JobrunrRecurringJobs as(Name alias) {
        return new JobrunrRecurringJobs(alias, this);
    }

    @Override
    public JobrunrRecurringJobs as(Table<?> alias) {
        return new JobrunrRecurringJobs(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public JobrunrRecurringJobs rename(String name) {
        return new JobrunrRecurringJobs(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JobrunrRecurringJobs rename(Name name) {
        return new JobrunrRecurringJobs(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public JobrunrRecurringJobs rename(Table<?> name) {
        return new JobrunrRecurringJobs(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JobrunrRecurringJobs where(Condition condition) {
        return new JobrunrRecurringJobs(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JobrunrRecurringJobs where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JobrunrRecurringJobs where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JobrunrRecurringJobs where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JobrunrRecurringJobs where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JobrunrRecurringJobs where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JobrunrRecurringJobs where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JobrunrRecurringJobs where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JobrunrRecurringJobs whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JobrunrRecurringJobs whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
