/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables;


import java.util.Arrays;
import java.util.List;

import org.eclipse.openvsx.jooq.Keys;
import org.eclipse.openvsx.jooq.Public;
import org.eclipse.openvsx.jooq.tables.records.QrtzCalendarsRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QrtzCalendars extends TableImpl<QrtzCalendarsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.qrtz_calendars</code>
     */
    public static final QrtzCalendars QRTZ_CALENDARS = new QrtzCalendars();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QrtzCalendarsRecord> getRecordType() {
        return QrtzCalendarsRecord.class;
    }

    /**
     * The column <code>public.qrtz_calendars.sched_name</code>.
     */
    public final TableField<QrtzCalendarsRecord, String> SCHED_NAME = createField(DSL.name("sched_name"), SQLDataType.VARCHAR(120).nullable(false), this, "");

    /**
     * The column <code>public.qrtz_calendars.calendar_name</code>.
     */
    public final TableField<QrtzCalendarsRecord, String> CALENDAR_NAME = createField(DSL.name("calendar_name"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>public.qrtz_calendars.calendar</code>.
     */
    public final TableField<QrtzCalendarsRecord, byte[]> CALENDAR = createField(DSL.name("calendar"), SQLDataType.BLOB.nullable(false), this, "");

    private QrtzCalendars(Name alias, Table<QrtzCalendarsRecord> aliased) {
        this(alias, aliased, null);
    }

    private QrtzCalendars(Name alias, Table<QrtzCalendarsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.qrtz_calendars</code> table reference
     */
    public QrtzCalendars(String alias) {
        this(DSL.name(alias), QRTZ_CALENDARS);
    }

    /**
     * Create an aliased <code>public.qrtz_calendars</code> table reference
     */
    public QrtzCalendars(Name alias) {
        this(alias, QRTZ_CALENDARS);
    }

    /**
     * Create a <code>public.qrtz_calendars</code> table reference
     */
    public QrtzCalendars() {
        this(DSL.name("qrtz_calendars"), null);
    }

    public <O extends Record> QrtzCalendars(Table<O> child, ForeignKey<O, QrtzCalendarsRecord> key) {
        super(child, key, QRTZ_CALENDARS);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<QrtzCalendarsRecord> getPrimaryKey() {
        return Keys.QRTZ_CALENDARS_PKEY;
    }

    @Override
    public List<UniqueKey<QrtzCalendarsRecord>> getKeys() {
        return Arrays.<UniqueKey<QrtzCalendarsRecord>>asList(Keys.QRTZ_CALENDARS_PKEY);
    }

    @Override
    public QrtzCalendars as(String alias) {
        return new QrtzCalendars(DSL.name(alias), this);
    }

    @Override
    public QrtzCalendars as(Name alias) {
        return new QrtzCalendars(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public QrtzCalendars rename(String name) {
        return new QrtzCalendars(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public QrtzCalendars rename(Name name) {
        return new QrtzCalendars(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, byte[]> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
