/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables;


import java.util.Arrays;
import java.util.List;

import org.eclipse.openvsx.jooq.Keys;
import org.eclipse.openvsx.jooq.Public;
import org.eclipse.openvsx.jooq.tables.records.QrtzSimpleTriggersRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QrtzSimpleTriggers extends TableImpl<QrtzSimpleTriggersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.qrtz_simple_triggers</code>
     */
    public static final QrtzSimpleTriggers QRTZ_SIMPLE_TRIGGERS = new QrtzSimpleTriggers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QrtzSimpleTriggersRecord> getRecordType() {
        return QrtzSimpleTriggersRecord.class;
    }

    /**
     * The column <code>public.qrtz_simple_triggers.sched_name</code>.
     */
    public final TableField<QrtzSimpleTriggersRecord, String> SCHED_NAME = createField(DSL.name("sched_name"), SQLDataType.VARCHAR(120).nullable(false), this, "");

    /**
     * The column <code>public.qrtz_simple_triggers.trigger_name</code>.
     */
    public final TableField<QrtzSimpleTriggersRecord, String> TRIGGER_NAME = createField(DSL.name("trigger_name"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>public.qrtz_simple_triggers.trigger_group</code>.
     */
    public final TableField<QrtzSimpleTriggersRecord, String> TRIGGER_GROUP = createField(DSL.name("trigger_group"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>public.qrtz_simple_triggers.repeat_count</code>.
     */
    public final TableField<QrtzSimpleTriggersRecord, Long> REPEAT_COUNT = createField(DSL.name("repeat_count"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.qrtz_simple_triggers.repeat_interval</code>.
     */
    public final TableField<QrtzSimpleTriggersRecord, Long> REPEAT_INTERVAL = createField(DSL.name("repeat_interval"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.qrtz_simple_triggers.times_triggered</code>.
     */
    public final TableField<QrtzSimpleTriggersRecord, Long> TIMES_TRIGGERED = createField(DSL.name("times_triggered"), SQLDataType.BIGINT.nullable(false), this, "");

    private QrtzSimpleTriggers(Name alias, Table<QrtzSimpleTriggersRecord> aliased) {
        this(alias, aliased, null);
    }

    private QrtzSimpleTriggers(Name alias, Table<QrtzSimpleTriggersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.qrtz_simple_triggers</code> table reference
     */
    public QrtzSimpleTriggers(String alias) {
        this(DSL.name(alias), QRTZ_SIMPLE_TRIGGERS);
    }

    /**
     * Create an aliased <code>public.qrtz_simple_triggers</code> table reference
     */
    public QrtzSimpleTriggers(Name alias) {
        this(alias, QRTZ_SIMPLE_TRIGGERS);
    }

    /**
     * Create a <code>public.qrtz_simple_triggers</code> table reference
     */
    public QrtzSimpleTriggers() {
        this(DSL.name("qrtz_simple_triggers"), null);
    }

    public <O extends Record> QrtzSimpleTriggers(Table<O> child, ForeignKey<O, QrtzSimpleTriggersRecord> key) {
        super(child, key, QRTZ_SIMPLE_TRIGGERS);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<QrtzSimpleTriggersRecord> getPrimaryKey() {
        return Keys.QRTZ_SIMPLE_TRIGGERS_PKEY;
    }

    @Override
    public List<UniqueKey<QrtzSimpleTriggersRecord>> getKeys() {
        return Arrays.<UniqueKey<QrtzSimpleTriggersRecord>>asList(Keys.QRTZ_SIMPLE_TRIGGERS_PKEY);
    }

    @Override
    public List<ForeignKey<QrtzSimpleTriggersRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<QrtzSimpleTriggersRecord, ?>>asList(Keys.QRTZ_SIMPLE_TRIGGERS__QRTZ_SIMPLE_TRIGGERS_SCHED_NAME_FKEY);
    }

    private transient QrtzTriggers _qrtzTriggers;

    public QrtzTriggers qrtzTriggers() {
        if (_qrtzTriggers == null)
            _qrtzTriggers = new QrtzTriggers(this, Keys.QRTZ_SIMPLE_TRIGGERS__QRTZ_SIMPLE_TRIGGERS_SCHED_NAME_FKEY);

        return _qrtzTriggers;
    }

    @Override
    public QrtzSimpleTriggers as(String alias) {
        return new QrtzSimpleTriggers(DSL.name(alias), this);
    }

    @Override
    public QrtzSimpleTriggers as(Name alias) {
        return new QrtzSimpleTriggers(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public QrtzSimpleTriggers rename(String name) {
        return new QrtzSimpleTriggers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public QrtzSimpleTriggers rename(Name name) {
        return new QrtzSimpleTriggers(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, String, Long, Long, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
