/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.eclipse.openvsx.jooq.Keys;
import org.eclipse.openvsx.jooq.Public;
import org.eclipse.openvsx.jooq.tables.records.ShedlockRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Shedlock extends TableImpl<ShedlockRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.shedlock</code>
     */
    public static final Shedlock SHEDLOCK = new Shedlock();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ShedlockRecord> getRecordType() {
        return ShedlockRecord.class;
    }

    /**
     * The column <code>public.shedlock.name</code>.
     */
    public final TableField<ShedlockRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.shedlock.lock_until</code>.
     */
    public final TableField<ShedlockRecord, LocalDateTime> LOCK_UNTIL = createField(DSL.name("lock_until"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.shedlock.locked_at</code>.
     */
    public final TableField<ShedlockRecord, LocalDateTime> LOCKED_AT = createField(DSL.name("locked_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.shedlock.locked_by</code>.
     */
    public final TableField<ShedlockRecord, String> LOCKED_BY = createField(DSL.name("locked_by"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private Shedlock(Name alias, Table<ShedlockRecord> aliased) {
        this(alias, aliased, null);
    }

    private Shedlock(Name alias, Table<ShedlockRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.shedlock</code> table reference
     */
    public Shedlock(String alias) {
        this(DSL.name(alias), SHEDLOCK);
    }

    /**
     * Create an aliased <code>public.shedlock</code> table reference
     */
    public Shedlock(Name alias) {
        this(alias, SHEDLOCK);
    }

    /**
     * Create a <code>public.shedlock</code> table reference
     */
    public Shedlock() {
        this(DSL.name("shedlock"), null);
    }

    public <O extends Record> Shedlock(Table<O> child, ForeignKey<O, ShedlockRecord> key) {
        super(child, key, SHEDLOCK);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<ShedlockRecord> getPrimaryKey() {
        return Keys.SHEDLOCK_PKEY;
    }

    @Override
    public List<UniqueKey<ShedlockRecord>> getKeys() {
        return Arrays.<UniqueKey<ShedlockRecord>>asList(Keys.SHEDLOCK_PKEY);
    }

    @Override
    public Shedlock as(String alias) {
        return new Shedlock(DSL.name(alias), this);
    }

    @Override
    public Shedlock as(Name alias) {
        return new Shedlock(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Shedlock rename(String name) {
        return new Shedlock(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Shedlock rename(Name name) {
        return new Shedlock(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, LocalDateTime, LocalDateTime, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
