/*
 * This file is generated by jOOQ.
 */
package org.eclipse.openvsx.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.eclipse.openvsx.jooq.Indexes;
import org.eclipse.openvsx.jooq.Keys;
import org.eclipse.openvsx.jooq.Public;
import org.eclipse.openvsx.jooq.tables.records.TrustedPublisherRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TrustedPublisher extends TableImpl<TrustedPublisherRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.trusted_publisher</code>
     */
    public static final TrustedPublisher TRUSTED_PUBLISHER = new TrustedPublisher();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TrustedPublisherRecord> getRecordType() {
        return TrustedPublisherRecord.class;
    }

    /**
     * The column <code>public.trusted_publisher.id</code>.
     */
    public final TableField<TrustedPublisherRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.trusted_publisher.namespace</code>.
     */
    public final TableField<TrustedPublisherRecord, Long> NAMESPACE = createField(DSL.name("namespace"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.trusted_publisher.extension_name</code>.
     */
    public final TableField<TrustedPublisherRecord, String> EXTENSION_NAME = createField(DSL.name("extension_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.trusted_publisher.provider</code>.
     */
    public final TableField<TrustedPublisherRecord, String> PROVIDER = createField(DSL.name("provider"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>public.trusted_publisher.registration</code>.
     */
    public final TableField<TrustedPublisherRecord, JSONB> REGISTRATION = createField(DSL.name("registration"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.trusted_publisher.claims</code>.
     */
    public final TableField<TrustedPublisherRecord, JSONB> CLAIMS = createField(DSL.name("claims"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.trusted_publisher.created_by</code>.
     */
    public final TableField<TrustedPublisherRecord, Long> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.trusted_publisher.created_timestamp</code>.
     */
    public final TableField<TrustedPublisherRecord, LocalDateTime> CREATED_TIMESTAMP = createField(DSL.name("created_timestamp"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private TrustedPublisher(Name alias, Table<TrustedPublisherRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TrustedPublisher(Name alias, Table<TrustedPublisherRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.trusted_publisher</code> table reference
     */
    public TrustedPublisher(String alias) {
        this(DSL.name(alias), TRUSTED_PUBLISHER);
    }

    /**
     * Create an aliased <code>public.trusted_publisher</code> table reference
     */
    public TrustedPublisher(Name alias) {
        this(alias, TRUSTED_PUBLISHER);
    }

    /**
     * Create a <code>public.trusted_publisher</code> table reference
     */
    public TrustedPublisher() {
        this(DSL.name("trusted_publisher"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.TRUSTED_PUBLISHER_NAMESPACE_IDX);
    }

    @Override
    public Identity<TrustedPublisherRecord, Long> getIdentity() {
        return (Identity<TrustedPublisherRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<TrustedPublisherRecord> getPrimaryKey() {
        return Keys.TRUSTED_PUBLISHER_PKEY;
    }

    @Override
    public List<ForeignKey<TrustedPublisherRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TRUSTED_PUBLISHER__TRUSTED_PUBLISHER_CREATED_BY_FKEY, Keys.TRUSTED_PUBLISHER__TRUSTED_PUBLISHER_NAMESPACE_FKEY);
    }

    @Override
    public TrustedPublisher as(String alias) {
        return new TrustedPublisher(DSL.name(alias), this);
    }

    @Override
    public TrustedPublisher as(Name alias) {
        return new TrustedPublisher(alias, this);
    }

    @Override
    public TrustedPublisher as(Table<?> alias) {
        return new TrustedPublisher(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TrustedPublisher rename(String name) {
        return new TrustedPublisher(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TrustedPublisher rename(Name name) {
        return new TrustedPublisher(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TrustedPublisher rename(Table<?> name) {
        return new TrustedPublisher(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrustedPublisher where(Condition condition) {
        return new TrustedPublisher(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrustedPublisher where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrustedPublisher where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrustedPublisher where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrustedPublisher where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrustedPublisher where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrustedPublisher where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrustedPublisher where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrustedPublisher whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrustedPublisher whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
