#!/bin/sh

# This script must be run from the 'server' directory
export OVSX_APP_PROFILE=$PWD/src/dev/resources/application-ovsx.properties

# Clear the content of the ovsx application profile
echo "# Generated by scripts/generate-properties.sh" > $OVSX_APP_PROFILE

# Set the Elasticsearch host
echo "ovsx.elasticsearch.host=localhost:9200" >> $OVSX_APP_PROFILE

# Set the web UI URL
if command -v gp > /dev/null
then
    echo "ovsx.webui.url=`gp url 3000`" >> $OVSX_APP_PROFILE
else
    echo "ovsx.webui.url=http://localhost:3000" >> $OVSX_APP_PROFILE
fi

# Set the OAuth2 client ids and client secrets
echo "spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID:-none}" >> $OVSX_APP_PROFILE
echo "spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET:-none}" >> $OVSX_APP_PROFILE
if [ -n "$ECLIPSE_CLIENT_ID" ] && [ -n "$ECLIPSE_CLIENT_SECRET" ]
then
    echo "spring.security.oauth2.client.registration.eclipse.client-id=$ECLIPSE_CLIENT_ID" >> $OVSX_APP_PROFILE
    echo "spring.security.oauth2.client.registration.eclipse.client-secret=$ECLIPSE_CLIENT_SECRET" >> $OVSX_APP_PROFILE
    echo "ovsx.eclipse.publisher-agreement.version=1" >> $OVSX_APP_PROFILE
fi

# Set the Google Cloud Storage project id and bucket id
if [ -n "$GCP_PROJECT_ID" ] && [ -n "$GCS_BUCKET_ID" ]
then
    echo "ovsx.storage.gcp.project-id=$GCP_PROJECT_ID" >> $OVSX_APP_PROFILE
    echo "ovsx.storage.gcp.bucket-id=$GCS_BUCKET_ID" >> $OVSX_APP_PROFILE
fi
