#!/usr/bin/env node

const semver = require('semver');

if (semver.lt(process.versions.node, '18.0.0')) {
    console.error('ovsx requires at least NodeJS version 18. Check your installed version with `node --version`.');
    process.exit(1);
}

require('./main')(process.argv);
