name: Gradle Dependency Submission
on:
  push:
    branches:
      - main
jobs:
  dependency-submission:
    name: Gradle dependency submission
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: github.repository == 'eclipse-openvsx/openvsx'
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      with:
          persist-credentials: false
    - name: Set up JDK
      uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961  # v5.7.0
      with:
        distribution: 'temurin'
        java-version: 25
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
      with:
        dependency-graph: 'generate-submit-and-upload'
    - run: server/gradlew --no-daemon -p server assemble
      env:
        DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: 'productionRuntimeClasspath'
