name: Gradle Dependency Submission
on:
  push:
    branches:
      - main
jobs:
  dependency-submission:
    name: Gradle dependency submission
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: github.repository == 'eclipse-openvsx/openvsx'
    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      with:
          persist-credentials: false
    - name: Set up JDK
      uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520  # v5.4.0
      with:
        distribution: 'temurin'
        java-version: 25
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
      with:
        dependency-graph: 'generate-submit-and-upload'
    - run: server/gradlew --no-daemon -p server assemble
      env:
        DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: 'productionRuntimeClasspath'
