name: Scorecard analysis workflow
on:
  push:
    branches:
    - main
  schedule:
    # Weekly on Saturdays.
    - cron:  '30 1 * * 6'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  analysis:
    if: github.repository_owner == 'eclipse-openvsx'
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: "Checkout code"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: "Run analysis"
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
