name: Sonar
on:
  push:
    branches:
      - main
jobs:
  sonar:
    name: Sonar
    permissions:
      contents: read
    runs-on: ubuntu-latest
    if: github.repository == 'eclipse-openvsx/openvsx'
    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      with:
          persist-credentials: false
          fetch-depth: 0
    - name: Cache SonarCloud packages
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Set up JDK
      uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a  # v5.5.0
      with:
        distribution: 'temurin'
        java-version: 25
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
    - name: Generate JaCoCo test report
      run: server/gradlew --no-daemon -p server jacocoTestReport
    - name: Make server libraries directory
      run: mkdir server/libraries
    - name: Copy server libraries
      run: find ~/.gradle/caches -type f -name '*.jar' -exec cp {} server/libraries \;
    - name: SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@713881670b6b3676cda39549040e2d88c70d582e  # v8.2.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
