name: Sonar
on:
  push:
    branches:
      - main
jobs:
  sonar:
    name: Sonar
    permissions:
      contents: read
    runs-on: ubuntu-latest
    if: github.repository == 'eclipse-openvsx/openvsx'
    steps:
    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
      with:
          persist-credentials: false
          fetch-depth: 0
    - name: Cache SonarCloud packages
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae  # v5.0.5
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Set up JDK
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654  # v5.2.0
      with:
        distribution: 'temurin'
        java-version: 25
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
    - name: Generate JaCoCo test report
      run: server/gradlew --no-daemon -p server jacocoTestReport
    - name: Make server libraries directory
      run: mkdir server/libraries
    - name: Copy server libraries
      run: find ~/.gradle/caches -type f -name '*.jar' -exec cp {} server/libraries \;
    - name: SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995  # v8.1.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
